2020-06-05 13:56:50,929 INFO: Knowland startup [in C:\Users\super\Knowland\app\__init__.py:83]
2020-06-05 14:00:39,838 INFO: Knowland startup [in C:\Users\super\Knowland\app\__init__.py:83]
2020-06-05 14:01:51,702 INFO: Knowland startup [in C:\Users\super\Knowland\app\__init__.py:83]
2020-06-05 14:02:31,078 INFO: Knowland startup [in C:\Users\super\Knowland\app\__init__.py:83]
2020-06-05 14:03:40,687 INFO: Knowland startup [in C:\Users\super\Knowland\app\__init__.py:83]
2020-06-05 14:05:42,710 INFO: Knowland startup [in C:\Users\super\Knowland\app\__init__.py:83]
2020-06-05 14:05:53,709 ERROR: Exception on /testgood [GET] [in c:\users\super\knowland\knowland_start\lib\site-packages\flask\app.py:1890]
Traceback (most recent call last):
  File "c:\users\super\knowland\knowland_start\lib\site-packages\flask\app.py", line 2446, in wsgi_app
    response = self.full_dispatch_request()
  File "c:\users\super\knowland\knowland_start\lib\site-packages\flask\app.py", line 1951, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "c:\users\super\knowland\knowland_start\lib\site-packages\flask\app.py", line 1820, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "c:\users\super\knowland\knowland_start\lib\site-packages\flask\_compat.py", line 39, in reraise
    raise value
  File "c:\users\super\knowland\knowland_start\lib\site-packages\flask\app.py", line 1949, in full_dispatch_request
    rv = self.dispatch_request()
  File "c:\users\super\knowland\knowland_start\lib\site-packages\flask\app.py", line 1935, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "c:\users\super\knowland\knowland_start\lib\site-packages\flask_login\utils.py", line 272, in decorated_view
    return func(*args, **kwargs)
  File "C:\Users\super\Knowland\app\main\routes.py", line 296, in testgood
    if answer1 == 'сходится':
NameError: name 'answer1' is not defined
2020-06-05 14:10:32,819 INFO: Knowland startup [in C:\Users\super\Knowland\app\__init__.py:83]
2020-06-05 14:11:11,344 INFO: Knowland startup [in C:\Users\super\Knowland\app\__init__.py:83]
2020-06-05 14:12:02,406 INFO: Knowland startup [in C:\Users\super\Knowland\app\__init__.py:83]
